### ISSUE TITLE
Done button in pushed view controller

### ISSUE THREAD

**Issue by federicocappelli** [justeat/JustTweak#27]
The TweaksConfigurationViewController has a "Done" button as rightBarButtonItem even if the VC has been pushed and not presented modally.

One possible way to improve it is to check if the VC has been presented modally before adding the Done button in `setupBarButtonItems()`.

```
func isModal() -> Bool {

        let presentingIsModal = presentingViewController != nil
        let presentingIsNavigation = navigationController?.presentingViewController?.presentedViewController == navigationController
        let presentingIsTabBar = tabBarController?.presentingViewController is UITabBarController

        return presentingIsModal || presentingIsNavigation || presentingIsTabBar
}
```

**Comment by ilazakis** [comment]
Hey @federicocappelli , long time no see 😄 It does make sense to only add the button if presenting modally according to the HIG, so yes, I think this is a good suggestion.

**Comment by federicocappelli** [comment]
@ilazakis heeeeeyyyy!! :) I was quite emotional writing down "pod Just..." in my Podfile ahah
Thanks, we are using JustTweak now and I'm sure I'm going to discover more corner cases.
Do you prefer to implement the changes internally or do you accept external pull requests?

**Comment by albertodebortoli** [comment]
👋 @federicocappelli this was something on our radar already but had no specific plan to change it. I've created a ticket in our backlog but external PRs are always welcome 😄

**Comment by federicocappelli** [comment]
Pr created https://github.com/justeat/JustTweak/pull/29

**Comment by albertodebortoli** [comment]
PR merged! 🙏
