### ISSUE TITLE
Crash when accessing tweak UI

### ISSUE THREAD

**Issue by Saurman** [justeat/JustTweak#80]
<img width="838" alt="Screenshot 2022-08-04 at 20 56 09" src="https://user-images.githubusercontent.com/1107926/182918638-e67d43e4-0659-41ba-a11d-724d586ae724.png">

**Comment by Saurman** [comment]
The issue was not present on 10.0.3 but appears on 10.1.0

**Comment by albertodebortoli** [comment]
We surely made changes in 10.1.0 giving priority to SPM over CocoaPods.
I've created a new project w/ CocoaPods but can't experience the crash:

<img width="734" alt="Screenshot 2022-08-05 at 09 50 13" src="https://user-images.githubusercontent.com/653112/183040709-e98ea06a-3b64-4dbb-8b68-8264ee01bbd2.png">
<img width="1120" alt="Screenshot 2022-08-05 at 09 49 46" src="https://user-images.githubusercontent.com/653112/183040727-04a6984a-879a-4f52-9250-10dcfee8d42d.png">

and the VC is presented correctly
<img width="984" alt="Screenshot 2022-08-05 at 09 52 32" src="https://user-images.githubusercontent.com/653112/183040997-9007f90c-b996-42f9-8aed-2c458e8fb0fe.png">

I get the same behaviour with either the following
```
pod 'JustTweak', :path => "../LocalPods/JustTweak/"
```
```
pod 'JustTweak', "10.1.0"
```

and I can fabricate the crash you reported by modifying the bundle id

<img width="858" alt="Screenshot 2022-08-05 at 09 55 12" src="https://user-images.githubusercontent.com/653112/183041787-d31e91c6-73f3-4cca-9a33-5dd9684036e7.png">


@Saurman can you give us more details to investigate?

**Comment by Saurman** [comment]
@albertodebortoli I am not sure what our issue is but I am unable to reproduce an issue anywhere except our application

**Comment by albertodebortoli** [comment]
Hi @Saurman I'm gonna go ahead and close this as we don't have enough info to reproduce. We are also about to deprecated and archive the repo as we moved to a different component ([Toggles](https://github.com/TogglesPlatform/Toggles)).
